# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ProcessKit' do
  use_frameworks!
end

target 'ProcessKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProcessCore
  pod "ProcessKit", :path => "../ProcessKit.podspec"
end
